version: "3.8"

services:
  #############################################
  # Appサーバ
  #############################################
  react-tsugou-kun-express:
    container_name: react-tsugou-kun-express
    build: 
      # appディレクトリの中から`Dockerfile`を探す
      context: ./backend
      # Dockerfileが期待する引数
      args:
        - HOST_URL=${HOST_URL}
        - COOKIE_EXPIRED_MINUTES=${COOKIE_EXPIRED_MINUTES:-86400}
    # nodeコマンド実行場所を指定
    working_dir: /opt/tsugou-kun/app/backend
    # サービス起動後に入力されるコマンドを設定
    # command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    # データを永続化させる場合の設定。`host:container`でパスを記載
    volumes:
      - ./backend/:/opt/tsugou-kun/app
    # 開放するポートを指定。`host:container`でポートを記載
    expose:
      - 3000
    # 環境変数を指定
    # environment:
    #   - DEBUG=0

  #############################################
  # Webサーバ
  #############################################
  react-tsugou-kun-nginx:
    container_name: react-tsugou-kun-nginx
    build:
      context: ./nginx
    environment:
      TZ: Asia/Tokyo
      LETSENCRYPT_HOSTS: tsugoukun.0g0.jp
      LETSENCRYPT_MAIL: isoittech@gmail.com
      LETSENCRYPT_SUBJECT: "/C=JP/ST=Tokyo/L=Shinagawa/CN=default"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-tsugou-kun-express
    volumes:
      # nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # log directory
      - /var/log/nginx:/var/log/nginx
      # document root directory
      #- /var/www/html:/var/www/html
      - ./backend:/opt/tsugou-kun/app
