version: "3.8"

services:
  #############################################
  # Appサーバ
  #############################################
  react-tsugou-kun-express:
    container_name: react-tsugou-kun-express
    build: 
      # appディレクトリの中から`Dockerfile`を探す
      context: ./backend
      # Dockerfileが期待する引数
      args:
        - HOST_URL=${HOST_URL}
        - COOKIE_EXPIRED_MINUTES=${COOKIE_EXPIRED_MINUTES:-86400}
    # nodeコマンド実行場所を指定
    working_dir: /opt/tsugou-kun/app/backend
    # サービス起動後に入力されるコマンドを設定
    command: node --nolazy -r ts-node/register/transpile-only src/index.ts
    #tty: true
    # 開放するポートを指定。`host:container`でポートを記載
    ports:
      - "3000:3000"

  #############################################
  # Webサーバ
  # ※HTTPSサイトとして公開するため https://github.com/isoittech/HttpsSiteRouter を利用している。
  #############################################
  react-tsugou-kun-nginx:
    container_name: react-tsugou-kun-nginx
    build:
      context: ./nginx
    environment:
      VIRTUAL_HOST: tsugoukun.0g0.jp # カンマ区切り指定
      LETSENCRYPT_HOST: tsugoukun.0g0.jp # カンマ区切り指定
      LETSENCRYPT_EMAIL: isoittech@gmail.com
    volumes:
      - ./html:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-tsugou-kun-express

networks:
  default:
    external:
      # "docker network create --driver bridge shared"
      # このコマンドを1ホストにつき1回実施すること。
      name: shared